language: node_js
node_js:
- '10'
script: npm run ci
cache: yarn
env:
  global:
    secure: kMCY/NrypncXWDgpTrOYbzWhU1WquxDY//9zFcLvD5nLlPR8xQ6qXPQ7/CZ2javowGjNauK4zgbiN53hfQyGly+T+Eqfl7kmOgUjxfwGEXQbPDAb0zmQA03VhTIEMJPWXmiKyVTSP9jFC0Ojlp3hxU8gq5fzy4u4+xFtRwe/iayZFRH+ECEW9L+bvGwxClFjooaZzZQjlMhGG1Wr9tm8hW3ML31QvN0sN5sMKOqdK1rJfHlg19e9uehm0/reGlZM33uuVNsBZhcGrC0GCND60lQUu1HTobkJeN5GnMD9QpRlSUBf4rFxSZnvwzHvt4vSDIsjuk+GTSPz+AbEQBhtmr57JwDdOfU9T1vL8UBNQJ/IEvYgbM7nsSSx7++OAVe04eozRmAB4mTEnH5Vrt6cItINX7LiIjENpyH/0otPiM2FEa5O23CeUnhjXzcrAtOTa2WTd2Tw5mp+98UnJZuocQ0Iqp1Vm+hdRDw1qmfqD7CmTVE7T64tSSbGQghPoSPkc9yV69tCUty6FL1W8eooVNy+eJBqXoI8J+TPRMynuNNeb8kHdraqXm08x4ZJiNaF8I+OUgd8TvE93EB5XA/J5ESII02+SwENRN6XwkrvY/1soqMSgyyOm8q0VYNjr8MHLaTIXJJTdYsDppOUHosyKTApY8twOwfjsM0fFM9tGWQ=
